modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "wiwismegatrees"
version = "${version}"
displayName = "Wiwi's Mega Trees"
authors = "lisarins"
description = '''
Adds mega tree variants for all vanilla trees
'''
#logoFile = ""

[[dependencies.wiwismegatrees]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wiwismegatrees]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
